build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Publish API project
        run: dotnet publish ./backend/FlexChat.API/FlexChat.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          - name: dotnet publish
        run: dotnet publish ./backend/FlexChat.API/FlexChat.API.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp